site_name: BAI x RTC NLP Slack Chatbot Documentation
site_url: "https://dhu2022-dev.github.io/BAI_RTC/"

theme:
  name: material

plugins:
  - search

nav:
  - Home: index.md
  - API Endpoints: api_endpoints.md
  - Architecture: architecture.md
  - Database Schema: database_schema.md
  - Deployment Guide: deployment.md
  - Usage Guide: usage_guide.md
